- lib/encoding/bufferwriter.js
was running some unit tests using `phantomjs`, got funky err:
```
TypeError: '*l' is not a valid argument for 'Function.prototype.apply' (evaluating 'new Array()')
```
this seemed like a logical fix
> avoid using Array.apply(new Array(), buf) for compatability

- README.md
The link to the community forum pointed to the old forum --- my as well
just take people to the new forum instead of having them be confused by
the old forum...
> update with the new link to the community forum

- lib/script/script.js
- lib/transaction/index.js
- lib/transaction/input/index.js
- lib/transaction/input/multisig.js
- lib/transaction/transaction.js
- test/transaction/input/multisig.js
code is more or less copy paste of P2SH multisig code with some changes.
also added `normalizeSignatures` to take existing signatures (as buffer, from a partially signed TX for example) and turn them into `TransactionSignature` instances, not sure what a good name would be, don't think `normalizeSignatures` is...
> Add support for bare multisig

- lib/crypto/signature.js
- test/crypto/signature.js
I was running this validation on test net and noticed even new transactions I was creating with the latest bitcoin client weren't validating correctly.
I've made the spec tests the boundaries of the low s/high s as well and cleaned it up a little there. Given BP62 is going more mainstream (more nodes running bitcoin 0.11.1 and 0.10.3) this might start to trip people up.
> hasLowS validation not using correct constant as it is set in base 10 rather than hex

- docs/networks.md
- lib/networks.js
- test/networks.js
Brings better compatibility between "testnet" and "regtest". Services such as
Bitcore Wallet Service and wallets such as Copay that have "testnet" and not
"regtest" will be compatible with "regtest" if enabled in a Bitcore node. This
adds two new API methods to enable/disable regtest on the testnet network:
- `bitcore.Networks.enableRegtest()`
- `bitcore.Networks.disableRegtest()`
Closes: https://github.com/bitpay/bitcore/issues/1190
> Networks: Added regtest to networks

- docs/address.md
Hi,
There is no `Address.Pay2PubKeyHash` property, instead it's `Address.PayToPublicKeyHash`.
> Fix wrong property name in docs (Address.Pay2PubKeyHash)

- lib/crypto/hash.js
- npm-shrinkwrap.json
- package.json
The sha512 library has not been updated in quite some time. This switches to
use Node.js crypto for sha512 that will use crypto-browserify, and more
recently maintained sha.js for the browser build.
> crypto: switch to Node.js sha512

- lib/script/script.js
- test/script/script.js
output type checks are pretty strict and would never match an input script, doing these checks first should give better results.
we ran into an issue where the data push of an opreturn started with `0x30` and was classified as script hash input because anything that starts with a `0x30` is matched as pubkey input.
eg `OP_RETURN OP_PUSH28 3630fd3792f7e847ae5e27985dfb127542ef37ac2a5147c3b9cec7ba` (`6a1c3630fd3792f7e847ae5e27985dfb127542ef37ac2a5147c3b9cec7ba`) is atm classified as "spends from script hash".
split `classify` into `classifyInput` / `classifyOutput` so user can be explicit too if he desire to be.
> `Script.classify` should first check output types before checking input types

- lib/transaction/transaction.js
The error message "Invalid state: undefined" is being given, that doesn't indicate the issue. This adds messages to assertions that have these left as undefined.
> Improve transaction assertion messages

- docs/crypto.md
Use the correct namespace case for 'crypto' modules
> Incorrect namespace for 'crypto' modules

- lib/block/blockheader.js
- lib/encoding/bufferreader.js
- lib/transaction/transaction.js
- test/block/blockheader.js
- test/transaction/transaction.js
https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers
https://en.bitcoin.it/wiki/Protocol_documentation#tx
The transaction and block version fields are both int32's (little endian encoded), so technically the range is -2^31 to 2^31 (not zero to 2^32)
> Transaction and block version are signed integers

- lib/transaction/transaction.js
Emphasis selectively disabling security checks vs using `uncheckedSerialize`, and update link to serialization check documentation to: https://bitcore.io/api/lib/transaction#serialization-checks
> transaction: update serialization skip docs

- lib/util/preconditions.js
Using "./buffer" fails on some browserify-esque platforms
such as Cordova and React.Native.
Fixes #108
> Directly use Buffer.isBuffer (Cordova, RN workaround)

- lib/networks.js
Closes https://github.com/bitpay/bitcore-lib/issues/193
Checked peer connections, and all of the networkMagic numbers in bitcore-lib/cash were referencing the diskMagic numbers. 
This is breaking p2p for Bitcoin ABC version v0.16.2.0, this PR should fix p2p.
> Updating cash network magic to match ABC

- lib/networks.js
- test/networks.js
* We need access to 'regtest' as a network
* dns and magic numbers from a single variable 
* stays backward compatible with testnet becoming regtest from enableRegtest
> Regtest Support

- lib/address.js
- lib/networks.js
- test/address.js
There were a few bugs with isValid(12345, 'regtest')
* returned false for regtest addresses after enableRegtest() was called
*  due to the testnet being selected as the network
* then the comparison was checking the entire object instead of the prefix
* since the network.name === 'testnet' the object compare returned false, since regtest was passed in. 
There were a few bugs with toCashAddress() on testnet addresses.
* concat on undefined due to testnet not having a prefixArray
* normally prefixArray is added when addNetwork is called but only if prefix is defined
* my previous refactor removed prefix for testnet and defined a dynamic property that toggles with enableRegtest()
* my prev refactor didn't define a dynamic property for prefixArray
Added tests for these scenarios
> isValid() / toCashAddr() Testnet support

- lib/address.js
- test/address.js
Supporting a common use-case, the cash address without the prefix on it.
> No prefix via toCashAddress(false)

- lib/networks.js
In a previous refactor the conversion to a buffer was removed
> Network magic property needs to be a buffer

- benchmark/script.js
- lib/address.js
- lib/block/block.js
- lib/block/blockheader.js
- lib/block/merkleblock.js
- lib/crypto/bn.js
- lib/crypto/ecdsa.js
- lib/crypto/hash.js
- lib/crypto/point.js
- lib/crypto/random.js
- lib/crypto/signature.js
- lib/encoding/base58.js
- lib/encoding/base58check.js
- lib/encoding/bufferreader.js
- lib/encoding/bufferwriter.js
- lib/encoding/varint.js
- lib/hdprivatekey.js
- lib/hdpublickey.js
- lib/opcode.js
- lib/privatekey.js
- lib/publickey.js
- lib/script/interpreter.js
- lib/script/script.js
- lib/transaction/sighash.js
- lib/transaction/signature.js
- lib/transaction/transaction.js
- lib/util/buffer.js
* new Buffer() is deprecated
* https://nodejs.org/api/buffer.html#buffer_new_buffer_array
* new Buffer([]) should be Buffer.from([])
* new Buffer(9) should be Buffer.alloc(9)
* BufferWriter should keep track of length as you write
* Transaction.hash getter should cache the last hash, until you change it.
Before Changes 
```
Benchmarking Script
---------------------------------------
isPublicKeyHashIn x 42,112,577 ops/sec ±2.14% (421 runs sampled)
isPublicKeyOut x 30,459,210 ops/sec ±2.80% (430 runs sampled)
toAddress x 65,897 ops/sec ±3.15% (323 runs sampled)
getAddressInfo x 86,997 ops/sec ±2.68% (325 runs sampled)
Done
----------------------------------------------------------------------
Finished
```
After Changes 
```
Benchmarking Script
--------------------------------------- …
```
> BCH  Buffer Update

- benchmark/script.js
- bitcore-lib.js
- lib/address.js
- lib/block/block.js
- lib/block/blockheader.js
- lib/block/merkleblock.js
- lib/crypto/bn.js
- lib/crypto/ecdsa.js
- lib/crypto/hash.js
- lib/crypto/point.js
- lib/crypto/random.js
- lib/crypto/signature.js
- lib/encoding/base58.js
- lib/encoding/base58check.js
- lib/encoding/bufferreader.js
- lib/encoding/bufferwriter.js
- lib/encoding/varint.js
- lib/hdprivatekey.js
- lib/hdpublickey.js
- lib/opcode.js
- lib/privatekey.js
- lib/publickey.js
- lib/script/interpreter.js
- lib/script/script.js
- lib/transaction/sighash.js
- lib/transaction/signature.js
- lib/transaction/transaction.js
- lib/util/buffer.js
* new Buffer() is deprecated
* https://nodejs.org/api/buffer.html#buffer_new_buffer_array
* new Buffer([]) should be Buffer.from([])
* new Buffer(9) should be Buffer.alloc(9)
* BufferWriter should keep track of length as you write
* Transaction.hash getter should cache the last hash, until you change it.
Before Changes 
```
Benchmarking Script
---------------------------------------
isPublicKeyHashIn x 42,112,577 ops/sec ±2.14% (421 runs sampled)
isPublicKeyOut x 30,459,210 ops/sec ±2.80% (430 runs sampled)
toAddress x 65,897 ops/sec ±3.15% (323 runs sampled)
getAddressInfo x 86,997 ops/sec ±2.68% (325 runs sampled)
Done
----------------------------------------------------------------------
Finished
```
After Changes 
```
Benchmarking Script
--------------------------------------- …
```
> Switching deprecated buffer constructor to use Buffer.from

- lib/address.js
- lib/networks.js
- test/address.js
when enableRegtest was called. I think that testnet addresses should return true under this scenario, and regtest addresses should only be valid when the network is expected to be regtest
> Testnet addresses were returning false for isValid 

- docs/examples.md
We shouldn't encourage use of `new Buffer()`. It's been deprecated for two years and if not used carefully can result in pretty major security vulnerabilities.
> Don't encourage use of `new Buffer()` in examples

- lib/transaction/input/multisig.js
- lib/transaction/input/multisigscripthash.js
- lib/transaction/transaction.js
During the creation of multisig outputs, it gives the option not to sort the public keys. However, it is not allowed to redeem unsorted public keys without interacting with the low level `addInput` function.
- Does not change the default behavior.
- Please push this to bitcore-lib-cash too.
@matiu
> Add "Don't sort option" to Multisig inputs - Can't redeem unsorted multisig pubkeys
